CREATE DATABASE HeThongThueXe_Nhom6
CREATE TABLE KhachHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma NVARCHAR(100) UNIQUE,
TenKH NVARCHAR(100) NULL,
GioiTinh BIT NULL,
NgaySinh DATE NULL,
CCCD NVARCHAR(100) NULL,
SDT NVARCHAR(100) NULL,
DiaChi NVARCHAR(100) NULL,
)
CREATE TABLE NhanVien(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma NVARCHAR(100) UNIQUE,
TenNV NVARCHAR(100) NULL,
VaiTro NVARCHAR(100) NULL,
CCCD NVARCHAR(100) NULL,
SDT NVARCHAR(100) NULL,
DiaChi NVARCHAR(100) NULL,
)
CREATE TABLE LoaiXe(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma NVARCHAR(100) UNIQUE,
TenLoai NVARCHAR(100) NULL,
SoLuong INT NULL,
MoTa NVARCHAR(1000) NULL,
)
CREATE TABLE XE(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
BienSo NVARCHAR(100) UNIQUE,
IdLoaiXe UNIQUEIDENTIFIER,
TenXe NVARCHAR(100) NULL,
PhiThueTrenNgay MONEY NULL,
MaTo NVARCHAR(1000) NULL,
TrangThai INT NULL
FOREIGN KEY (IdLoaiXe) REFERENCES LoaiXe(Id)
)
CREATE TABLE LichDatXe(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma NVARCHAR(100) UNIQUE,
IdKhachHang UNIQUEIDENTIFIER,
IdXe UNIQUEIDENTIFIER,
NgayNhan DATE NULL,
NgayTra DATE NULL,
KhuVuc NVARCHAR(100) NULL,
FOREIGN KEY (IdKhachHang) REFERENCES KhachHang(Id),
FOREIGN KEY (IdXe) REFERENCES Xe(Id)
)
CREATE TABLE HopDongThueXe(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma NVARCHAR(100) UNIQUE,
IdLichDat UNIQUEIDENTIFIER,
IdNV UNIQUEIDENTIFIER,
LoaiHD NVARCHAR(100) NULL,
NgayKyHD DATE NULL,
NoiDungHD NVARCHAR(1000) NULL,
SoNgayThue INT NULL,
GiayToGiuLai NVARCHAR(1000) NULL,
TienDatCoc MONEY NULL,
KhuyenMai MONEY NULL,
MoTa NVARCHAR(1000) NULL,
FOREIGN KEY (IdNV) REFERENCES NhanVien(Id),
FOREIGN KEY (IdLichDat) REFERENCES LichDatXe(Id),
)
CREATE TABLE LichGiaHanHD(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHD UNIQUEIDENTIFIER,
SoNgayGiaHan NVARCHAR(100) NULL,
MoTa NVARCHAR(100) NULL,
FOREIGN KEY (IdHD) REFERENCES HopDongThueXe(Id),
) 
CREATE TABLE BienBan(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma NVARCHAR(100) UNIQUE,
IdHD UNIQUEIDENTIFIER,
TinhTrangXe NVARCHAR(100) NULL,
NgayTraXe NVARCHAR(100) NULL,
MoTa NVARCHAR(1000) NULL,
FOREIGN KEY (IdHD) REFERENCES HopDongThueXe(Id),
)
CREATE TABLE HanhViVP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma NVARCHAR(100) UNIQUE,
IdHD UNIQUEIDENTIFIER,
NDViPham NVARCHAR(1000) NULL,
SoTienPhat MONEY NULL,
MoTa NVARCHAR(100) NULL,
FOREIGN KEY (IdHD) REFERENCES HopDongThueXe(Id),
)
CREATE TABLE HoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHD UNIQUEIDENTIFIER,
IdLichGiaHan UNIQUEIDENTIFIER,
IdBienBan UNIQUEIDENTIFIER,
IdViPham UNIQUEIDENTIFIER,
IdNhanVien UNIQUEIDENTIFIER,
NgayTao DATE NULL,
TinhTrang DATE NUll,
FOREIGN KEY (IdHD) REFERENCES HopDongThueXe(Id),
FOREIGN KEY (IdLichGiaHan) REFERENCES LichGiaHanHD(Id),
FOREIGN KEY (IdBienBan) REFERENCES BienBan(Id),
FOREIGN KEY (IdViPham) REFERENCES HanhViVP(Id),
FOREIGN KEY (IdNhanVien) REFERENCES NhanVien(Id)
)
